# Generated by Django 5.1.3 on 2024-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, max_length=12)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("primary_skill", models.CharField(max_length=50)),
                ("addl_skill", models.CharField(max_length=50)),
                ("activation_code", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
